# Generated by Django 4.0.1 on 2022-01-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verzelapp', '0003_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['nome']},
        ),
    ]
